Tue Aug 31 02:03:42 2021 << Running
Tue Aug 31 02:02:07 2021 << Last Update
Atlanta - Emergency Stop: False
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "app.py", line 223, in bot_live_update
  File "requests\models.py", line 900, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Bot live False
Bot idle True
Bot print True
Bot print ended!!!